import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import "./globals.css";

const dinTextPro = localFont({
  src: [
    {
      path: "./fonts/PFDinTextPro-Regular.ttf", // Adjust path to your actual files
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/PFDinTextPro-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-din-text", 
});

export const metadata: Metadata = {
  title: "The UK Hotel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${dinTextPro.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}